name: Arduino CLI Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Arduino CLI
    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        arduino-cli version

    # Configure Arduino CLI
    - name: Configure Arduino CLI
      run: |
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-cli core update-index
        arduino-cli core install esp32:esp32@3.0.2

    # Compile the firmware
    - name: Compile Firmware
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 --build-path ./build main/main.ino